---
title: "lab_4"
author: "Claire Meuter"
date: "2023-02-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(knitr)
library(kableExtra)
library(tictoc)
library(furrr)
```

```{r}
map(.x,  # What are we evaluating or passing through to a function?
    .f,  # The function itself
    ...  # Extra features for the function or mapping options
    )
```

```{r}
mtcars %>% 
  map(mean)%>%  #taking the mean across a bunch of columns. Fast, easier to set up than a four loop 
  kable() %>% 
  kable_classic()
```
```{r}
mtcars %>% 
  map_dbl(mean) %>%  # dbl is short for double e.g numbers
  head() %>% kable() %>%
  kable_classic()
```
Imagine you are tasked with running regressions over subsets of data each with different regressions specifications how would you do it?
```{r}
mod1=lm(y~x,data=filter(thing1,df))
mod2=lm(y~x,data=filter(thing2,df))
```

Map can apply regressions to any number of subsets
```{r}
mtcars %>% 
  split(mtcars$cyl) %>%   #split is a base R so not part of the tidyverse, sort of like groupby 
  map(~lm(mpg~wt,data = .)) # the . is passed from the pipe with .x of map
```
Only 3 cylinders in the dataset, but there could have been 1,000 and the code above would store 1,000 regression models

```{r}
map2(.x,  # dataset 1
     .y,  # dataset 2
     .f(x,y,...),  # the function the accepts dataset1 and dataset2 
     ...
     )
```

```{r}
by_cyl <- mtcars %>%  split(mtcars$cyl)  # Store the dataset for predictions
mods <- by_cyl %>%  map(~lm(mpg ~ wt, data = .))
predictions<-map2(mods, by_cyl, predict) # Take my linear mods and use the data to predict mpg
```

